source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :test do
    gem "capybara", "~> 3.35"
    gem "rspec", "~> 3.10"
    gem 'selenium-webdriver'
end
