name: CI

on:
  push:
    branches: [ 1_create_pack ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: 'Install Yarn'
        run: ./gradlew yarn_install

      - name: 'Test React app'
        run: ./gradlew yarn_test

      - name: 'Test Spring app'
        run: ./gradlew test

      - name: 'Build JAR'
        run: |
          ./gradlew yarn_build
          ./gradlew copyStaticJSResources
          ./gradlew build

      - name: 'Save built jar artifact'
        uses: actions/upload-artifact@v1
        with:
          name: application-jar
          path: build/libs

      - name: 'Set Heroku login credentials'
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - name: 'Deploy to Heroku'
        run: |
          heroku plugins:install java
          heroku deploy:jar build/libs/gear-packer-0.0.1-SNAPSHOT.jar --app ${{ secrets.HEROKU_APP_NAME }}
