name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: 'Build and Test Spring app'
        run: ./gradlew build

      - name: 'Save built jar artifact'
        uses: actions/upload-artifact@v1
        with:
          name: application-jar
          path: build/libs

      - name: 'Test React app'
        run: |
          yarn install
          yarn ci
          yarn test

      - name: 'Build React app'
        run: yarn build

#      - name: 'Set up Ruby 2.6'
#        uses: ruby/setup-ruby@v1
#        env:
#          BUNDLE_GEMFILE: src/test/integration/Gemfile
#        with:
#          ruby-version: 2.6
#          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

#      - name: 'Run Integration tests with Rspec'
#        run:  |
#          docker-compose up -d --build
#          ./gradlew integration

      - name: 'Set Heroku login credentials'
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - name: 'Deploy to Heroku'
        run: |
          heroku plugins:install java
          heroku deploy:jar build/libs/gear-packer-0.0.1-SNAPSHOT.jar --app ${{ secrets.HEROKU_APP_NAME }}
