name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: 'Build and Test Spring app'
        run: ./gradlew build

      - name: 'Test React app'
        run: ./gradlew yarn_test

      - name: 'Run Integration tests with Rspec'
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GEMFILE: src/test/integration/Gemfile
        with:
          ruby-version: 2.6
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        run:  |
          docker-compose up
          ./gradlew integration

      - name: 'Deploy to Heroku'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          healthcheck: https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/actuator/health
          # Needed so heroku can start up from sleep
          # it's quite a long wait, so in the future reevaluate if this is actually helpful
          delay: 20 # (in seconds)
